#!/usr/bin/env python

# This file is for building as a Godot module.

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_4d = env_modules.Clone()

env_4d.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_4d.add_source_files(env.modules_sources, "editor/*.cpp")
