#!/usr/bin/env python

Import("env")
Import("env_modules")

env_4d = env_modules.Clone()

env_4d.GLSL_HEADER("cross_section/tetra_cross_section_shader.glsl")
env_4d.GLSL_HEADER("shaders/tetra_light_shader.glsl")
env_4d.GLSL_HEADER("shaders/wireframe_shader_3d.glsl")

env_4d.add_source_files(env.modules_sources, "*.cpp")
env_4d.add_source_files(env.modules_sources, "cross_section/*.cpp")

# The combined and projected engines require RenderingDevice, which not all platforms have.
if env["rendering_device"]:
    env_4d.GLSL_HEADER("combined/depth_capture.glsl")
    env_4d.GLSL_HEADER("projected/normalize_transparency.glsl")
    env_4d.GLSL_HEADER("projected/tetra_projected_shader.glsl")

    env_4d.add_source_files(env.modules_sources, "combined/*.cpp")
    env_4d.add_source_files(env.modules_sources, "projected/*.cpp")
