#pragma once

#include "../math/rect4i.h"
#include "../model/mesh/mesh_instance_4d.h"
#include "voxel_constants.h"

#if GDEXTENSION
#include <godot_cpp/templates/hash_map.hpp>
#include <godot_cpp/templates/hash_set.hpp>
#elif GODOT_MODULE
#include "core/templates/hash_map.h"
#include "core/templates/hash_set.h"
#endif

class VoxelWorld4D;

// Keeps track of the chunk meshes of one VoxelWorld4D: which have been
// generated, and which are dirty and need regenerating. This is conceptually
// part of VoxelWorld4D, split into its own class for readability.
class VoxelMeshHandler {
	VoxelWorld4D *const _world;
	// All existing chunk meshes, keyed by the lowest voxel coordinate of the
	// VOXEL_MESH_CHUNK_SIZE hypercube of voxel space each mesh covers.
	HashMap<Vector4i, MeshInstance4D *> _chunk_meshes;
	// The positions of mesh chunks whose meshes no longer match the voxel data.
	HashSet<Vector4i> _dirty_chunks;

public:
	// Records that the voxel values inside the given region, and the surface
	// normals of the edges inside it or on its surface (including edges just
	// below its lower surfaces), may have changed. The meshes reading any of
	// that data, those of the chunks overlapping the region grown by 1, are
	// regenerated by the next update_dirty_meshes call.
	void mark_region_dirty(const Rect4i &p_region);

	// Regenerates the meshes of a bounded number of dirty chunks, keeping the
	// rest dirty for later calls, and creates and removes mesh instances as
	// chunks change between empty and non-empty. Chunks whose region is not
	// entirely defined get no mesh. Called every tick by the VoxelWorld4D.
	void update_dirty_meshes();

	explicit VoxelMeshHandler(VoxelWorld4D *p_world) :
			_world(p_world) {}
};
