#!/usr/bin/env python

Import("env")
Import("env_modules")

env_4d = env_modules.Clone()

env_4d.add_source_files(env.modules_sources, "*.cpp")
env_4d.add_source_files(env.modules_sources, "bodies/*.cpp")
env_4d.add_source_files(env.modules_sources, "server/*.cpp")
env_4d.add_source_files(env.modules_sources, "shapes/*.cpp")
