#!/usr/bin/env python

Import("env")
Import("env_modules")

env_4d = env_modules.Clone()

env_4d.GLSL_HEADER("cross_section/tetra_cross_section_light_shader.glsl")
env_4d.GLSL_HEADER("cross_section/tetra_cross_section_shader.glsl")
env_4d.GLSL_HEADER("cross_section/wireframe_cross_section_shader.glsl")
env_4d.GLSL_HEADER("environment/sky/gradient_sky_shader.glsl")
env_4d.GLSL_HEADER("environment/sky/physical_sky_shader.glsl")
env_4d.GLSL_HEADER("environment/sky/plain_sky_shader.glsl")

env_4d.add_source_files(env.modules_sources, "*.cpp")
env_4d.add_source_files(env.modules_sources, "cross_section/*.cpp")
env_4d.add_source_files(env.modules_sources, "environment/*.cpp")
env_4d.add_source_files(env.modules_sources, "environment/sky/*.cpp")
env_4d.add_source_files(env.modules_sources, "wireframe_canvas/*.cpp")
